#!/bin/sh

set -e

echo "Running postinst for noel with $1"
if  [ "$1" = configure ]; then
  # creating a desktop item
  xdg-desktop-menu install /opt/noel/lib/noel-NoEl.desktop
  # creating a link, so the application can be called from the command line
  ln -sf /opt/noel/bin/NoEl /bin/noel
fi

exit 0
