name: build all targets

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      version:
        required: true
        type: string
      prerelease:
        required: true
        type: boolean

jobs:
  verify:
    uses: ./.github/workflows/verify.yaml

  build-to-fat-jar:
    needs: verify
    uses: ./.github/workflows/fat-jar.yaml
    with:
      tag: ${{ inputs.tag }}
      prerelease: ${{ inputs.prerelease }}
    secrets: inherit

  #build-with-jlink-jpackage:
  #  needs: verify
  #  uses: ./.github/workflows/jlink-jpackage.yaml
  #  with:
  #    tag: ${{ inputs.tag }}
  #    version: ${{ inputs.version }}
  #    prerelease: ${{ inputs.prerelease }}
  #  secrets: inherit

  build-with-jar-jpackage:
    needs: verify
    uses: ./.github/workflows/jar-jpackage.yaml
    with:
      tag: ${{ inputs.tag }}
      version: ${{ inputs.version }}
      prerelease: ${{ inputs.prerelease }}
    secrets: inherit
