name: dev-build all targets

on:
  push:
    branches:
      - develop

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      tag: dev
      version: 0.1
      prerelease: true
    secrets: inherit
