name: JAR with Dependencies Build

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      prerelease:
        required: true
        type: boolean

jobs:
  build-to-fat-jar:
    name: Build on ${{ matrix.os.name }} to fat jar
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, file-mod: "linux" },
          { name: windows-latest, file-mod: "win" }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Prepare project
        run: |
          rm src/main/java/module-info.java

      - name: Build with Maven
        run: |
          mvn -P fat-jar --batch-mode --update-snapshots clean install package

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/noel.jar
          asset_name: noel-${{ matrix.os.file-mod }}.jar
          overwrite: true
          tag: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          release_name: ${{ inputs.tag }}
