name: tagged-version build all targets

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      tag: ${GITHUB_REF#refs/*/}
      version: ${GITHUB_REF:11}
      prerelease: false
    secrets: inherit
