name: tagged-version build all targets

on:
  push:
    tags:
      - '*.*'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      tag: ${{ github.ref_name }}
      version: ${{ github.ref_name }}
      prerelease: false
    secrets: inherit
